prometheus-operator:
  prometheus:
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        certmanager.k8s.io/cluster-issuer: letsencrypt-prod
      hosts:
        - prometheus.example.com
      tls:
        - hosts:
            - prometheus.example.com
          secretName: prometheus-example-com-tls

  grafana:
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        certmanager.k8s.io/cluster-issuer: letsencrypt-prod
      hosts:
        - grafana.example.com
      tls:
        - hosts:
            - grafana.example.com
          secretName: grafana-example-com-tls
