apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dummy-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:eytanhanig/argocd-example.git
    path: apps/dummy-app
    targetRevision: master
  destination:
    server: https://kubernetes.default.svc
    namespace: dummy-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
